/* Automatically generated by './build/bin/build-entry.js' */
import OaFormDivider from '../packages/form-divider/index.js';
import OaBackToTop from '../packages/back-to-top/index.js';
import OaRemoteSelect from '../packages/remote-select/index.js';
import OaFormValue from '../packages/form-value/index.js';
import OaUploaderFile from '../packages/uploader-file/index.js';
import OaSelectCheck from '../packages/select-check/index.js';
import OaSelectHuge from '../packages/select-huge/index.js';
import OaLogSteps from '../packages/log-steps/index.js';
import OaTable from '../packages/table/index.js';
import OaTableForm from '../packages/table-form/index.js';
import OaTableList from '../packages/table-list/index.js';
const components = [
  OaFormDivider,
  OaBackToTop,
  OaRemoteSelect,
  OaFormValue,
  OaUploaderFile,
  OaSelectCheck,
  OaSelectHuge,
  OaLogSteps,
  OaTable,
  OaTableForm,
  OaTableList
];
const install = function(Vue) {
  components.forEach(component => {
    Vue.component(component.name, component);
  });
};
/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}
export default {
  version: '0.1.4',
  install,
  OaFormDivider,
  OaBackToTop,
  OaRemoteSelect,
  OaFormValue,
  OaUploaderFile,
  OaSelectCheck,
  OaSelectHuge,
  OaLogSteps,
  OaTable,
  OaTableForm,
  OaTableList
};
